import argparse
from pathlib import Path

import matplotlib

#Backend that works without graphical display
#Do before importing pyplot
matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
import pandas as pd

def plot_training_curves(history_path, title):
    history_path = Path(history_path)
    history = pd.read_csv(history_path)

    required_columns = [
        "epoch",
        "train_loss",
        "val_loss",
        "train_auroc",
        "val_auroc",
        "train_accuracy",
        "val_accuracy",
    ]

    missing = [
        column
        for column in required_columns
        if column not in history.columns
    ]

    if missing:
        raise ValueError(
            f"Missing columns: {missing}."
            "Use a history generated by the updated training script."
        )

    if history.empty:
        raise ValueError("The training history contains no epochs.")

    for column in required_columns:
        history[column] = pd.to_numeric(
            history[column],
            errors="raise",
        )

    history = history.sort_values("epoch")

    fig, axes = plt.subplots(
        1,
        3,
        figsize=(15, 4.5),
        constrained_layout=True,
    )

    fig.suptitle(f"{title} - series-level performance")

    panels = [
        ("loss", "Binary cross-entropy loss"),
        ("auroc", "AUROC"),
        ("accuracy", "Accuracy"),
    ]

    for ax, (metric, ylabel) in zip(axes, panels):
        ax.plot(
            history["epoch"],
            history[f"train_{metric}"],
            label="Training",
            color="tab:blue",
            marker="o",
            markersize=3,
        )

        ax.plot(
            history["epoch"],
            history[f"val_{metric}"],
            label="Validation",
            color="tab:orange",
            marker="o",
            markersize=3,
        )

        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.xaxis.set_major_locator(MaxNLocator(integer=True))
        ax.grid(alpha=0.3)

        if metric == "auroc":
            ax.axhline(
                0.5,
                color="gray",
                linestyle="--",
                label="Chance AUROC",
            )

        if metric in ("auroc", "accuracy"):
            ax.set_ylim(0, 1)

        ax.legend()

    #Keep each method's results seperate, save beside the CSV
    try: 
        for extension in ("png", "pdf"):
            output_path = history_path.parent / (
                f"training_curves.{extension}"
            )

            fig.savefig(output_path, dpi=200)
            print(f"Saved: {output_path}")
    finally:
        plt.close(fig)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Save training and validation curves from a CSV."
    )

    parser.add_argument(
        "history",
        help="Path to training_history.csv",
    )

    parser.add_argument(
        "--title",
        default="RV/LV classifier",
        help="Title displayed above the pltos",
    )

    args = parser.parse_args()
    plot_training_curves(args.history, args.title)

# Linear probing:
# python ventricle_project/plot_training_curves.py ventricle_project/results/linear_probe_rvlv/training_history.csv --title "Linear probing"

# Fine-tuning:
# python ventricle_project/plot_training_curves.py ventricle_project/results/finetune_rvlv/training_history.csv --title "Fine-tuning"